### ISSUE TITLE
Matlab fails to build with Python 3

### ISSUE THREAD

**Issue by nordmoen** [easybuilders/easybuild-easyblocks#2329]
Trying to build `matlab-2020b` with system version `Python 3.6` fails to configure the build.

The error is caused by [reading a non-ascii character](https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-master/easybuild/easyconfigs/m/MATLAB/MATLAB-2020a-remove-idiotic-non-ascii-character.patch).

**Comment by nordmoen** [comment]
Should be solved by [#3565](https://github.com/easybuilders/easybuild-framework/pull/3565)

**Comment by boegel** [comment]
Turns out https://github.com/easybuilders/easybuild-framework/pull/3565 doesn't actually fix this issue, because it's a non-UTF-8 character... 🤦 

This will need some work in the MATLAB easyblock, on it...
